services:
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: planazo
      POSTGRES_PASSWORD: planazo_dev_123
      POSTGRES_DB: planazo
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://planazo:planazo_dev_123@db:5432/planazo
      SESSION_SECRET: tu_secreto_de_sesion_aqui
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    command: npm run dev -- --inspect=0.0.0.0:9229
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000/api # es lo que usa Axios desde el navegador.
      BACKEND_URL: http://backend:4000 # url interna que usa el rewrite del servidor de next.js. No lleva nex_public para que no se exponga al navegador
      WATCHPACK_POLLING: "true"   
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

volumes:
  pgdata:
